import axios from 'axios'

// Node shapes come from the ontology registry, generated by ./gradlew generateOntology. Declaring
// them here as well is how the model used to drift between backend and frontend, so these are
// re-exported rather than restated. See docs/ONTOLOGY.md.
export type {
  Repository,
  Team,
  Service,
  Pipeline,
  Artifact,
  Deployment,
  Environment,
  CloudResource,
  ConfigurationItem,
  Provenance,
  NodeType,
  EdgeTypeName
} from '@/generated/ontology'
export { NODE_TYPES, EDGE_TYPES, ONTOLOGY_VERSION } from '@/generated/ontology'

import type {
  Repository,
  Team,
  Deployment,
  CloudResource,
  NodeType,
  EdgeTypeName,
  Provenance
} from '@/generated/ontology'

/**
 * The one HTTP client every call goes through. Exported so the consumer contract tests can point it
 * at a Pact mock server and exercise the real API functions rather than a copy of them.
 */
export const apiClient = axios.create({ baseURL: '/api/v1' })

const client = apiClient

export interface ImpactAnalysis {
  repoId: string
  dependents: Repository[]
  cloudResources: CloudResource[]
  deployments: Deployment[]
}

/**
 * What a caller supplies when registering a repository.
 *
 * `host`, `org` and `name` are absent on purpose: the API parses them out of `url`, which may be
 * written in any remote notation. Asking for them here would invite a caller to split the remote
 * themselves, and a caller who splits it differently is how one repository becomes two nodes (#8).
 */
export type NewRepository = Omit<Repository, 'id' | 'host' | 'org' | 'name'>

/**
 * A repository as the repository endpoints render it (#88): its key, the keys it had before a rename,
 * and `orgRepo`, still emitted for callers that read it though no longer accepted.
 */
export type RepositoryRecord = Repository & {
  key: string
  orgRepo: string
  previousKeys: string[]
}

export const repositoryApi = {
  list: (): Promise<Repository[]> => client.get('/repositories').then(r => r.data),
  get: (id: string): Promise<Repository> => client.get(`/repositories/${id}`).then(r => r.data),
  /**
   * Finds a repository by the key it resolves to, in any remote notation.
   *
   * The API normalises the key with the same parser that produced the stored one, so `Acme/Payments`
   * finds the node held as `github.com/acme/payments` (#8).
   */
  byKey: (key: string): Promise<Repository> =>
    client.get('/repositories/by-key', { params: { key } }).then(r => r.data),
  /**
   * Finds a repository by the id its provider gives it, such as GitHub's repository id, which
   * survives a rename or a transfer where the remote does not (#88).
   */
  byProvider: (provider: string, providerId: string): Promise<RepositoryRecord> =>
    client
      .get(
        `/repositories/by-provider/${encodeURIComponent(provider)}/${encodeURIComponent(providerId)}`
      )
      .then(r => r.data),
  /**
   * The repository a remote resolves to, as a list of at most one: the remote may be one the
   * repository had before a rename (#88).
   */
  byUrl: (url: string): Promise<RepositoryRecord[]> =>
    client.get('/repositories', { params: { url } }).then(r => r.data),
  create: (repo: NewRepository): Promise<Repository> =>
    client.post('/repositories', repo).then(r => r.data),
  delete: (id: string): Promise<void> => client.delete(`/repositories/${id}`).then(() => undefined),
  linkToTeam: (repoId: string, teamId: string): Promise<void> =>
    client.post(`/repositories/${repoId}/teams/${teamId}`).then(() => undefined),
  addDependency: (repoId: string, depRepoId: string): Promise<void> =>
    client.post(`/repositories/${repoId}/dependencies/${depRepoId}`).then(() => undefined)
}

export const graphApi = {
  getCloudResources: (repoId: string): Promise<CloudResource[]> =>
    client.get(`/graph/repositories/${repoId}/cloud-resources`).then(r => r.data),
  getDependencies: (repoId: string): Promise<Repository[]> =>
    client.get(`/graph/repositories/${repoId}/dependencies`).then(r => r.data),
  getDependents: (repoId: string): Promise<Repository[]> =>
    client.get(`/graph/repositories/${repoId}/dependents`).then(r => r.data),
  getDeployments: (repoId: string): Promise<Deployment[]> =>
    client.get(`/graph/repositories/${repoId}/deployments`).then(r => r.data),
  getTeam: (repoId: string): Promise<Team | null> =>
    client
      .get(`/graph/repositories/${repoId}/team`)
      .then(r => r.data)
      .catch(() => null),
  getImpact: (repoId: string): Promise<ImpactAnalysis> =>
    client.get(`/graph/repositories/${repoId}/impact`).then(r => r.data),
  getServiceNowCI: (repoId: string): Promise<ServiceNowCI | null> =>
    client
      .get(`/graph/repositories/${repoId}/servicenow`)
      .then(r => r.data)
      .catch(() => null),
  /**
   * The neighbourhood of a node, for the graph view (#9, FR11). The node is a query parameter
   * because its key holds '/'; type filters are sent comma separated, and only when there are any.
   */
  neighbourhood: (query: NeighbourhoodQuery): Promise<Subgraph> =>
    client
      .get('/graph/neighbourhood', {
        params: {
          nodeId: query.nodeId,
          depth: query.depth ?? 1,
          nodeTypes: query.nodeTypes?.length ? query.nodeTypes.join(',') : undefined,
          edgeTypes: query.edgeTypes?.length ? query.edgeTypes.join(',') : undefined,
          direction: query.direction ?? 'both'
        }
      })
      .then(r => r.data)
}

/** One hop of the path that explains why a node is in a blast radius, named as it was walked. */
export interface ImpactPathStep {
  edge: string
  from: string
  to: string
  confidence: number
  inferred: boolean
}

/** A node a change reaches (#21), with the most confident path that reaches it. */
export interface AffectedNode {
  node: { id: string; type: string; key: string; props: Record<string, unknown> }
  distance: number
  confidence: number
  inferred: boolean
  path: ImpactPathStep[]
}

/**
 * `GET /api/v1/graph/impact` (#21): what a change to `root` reaches downstream. `byType` counts every
 * affected node by type, past the listing cap, and `excluded` those below `minConfidence`.
 */
export interface ImpactResult {
  root: { id: string; type: string; key: string }
  depth: number
  direction: string
  minConfidence: number
  truncated: boolean
  affected: AffectedNode[]
  byType: Record<string, number>
}

/**
 * The blast radius of #21, which the graph view overlays (#9, FR8). Its depth is 1 to 5 and its
 * confidence floor 0 to 1; the view asks at its own depth, which is at most 3.
 */
export const impactApi = {
  impact: (nodeId: string, depth: number, minConfidence: number): Promise<ImpactResult> =>
    client.get('/graph/impact', { params: { nodeId, depth, minConfidence } }).then(r => r.data)
}

/** An environment a deployment targeted, with the tier it is weighted by. */
export interface LineageEnvironment {
  id: string
  key: string
  tier: string
}

/** A commit a deployment carries (#85). */
export interface LineageChange {
  id: string
  sha?: string
  repositoryKey?: string
  title?: string
}

/** A work item as a reference to the system that owns it (ADR-0012). */
export interface LineageWorkItem {
  id: string
  uri: string
  system?: string
  externalKey?: string
  title?: string
}

/** A deployment a work item is live in, with the artifacts and changes that carry it there. */
export interface LiveDeployment {
  id: string
  deployedAt?: string
  status?: string
  environment?: LineageEnvironment
  artifacts: { id: string }[]
  changes: LineageChange[]
}

/** Where a work item is live (#85), most recent deployment first. */
export interface WorkItemDeployments {
  workItem: LineageWorkItem
  deployments: LiveDeployment[]
}

/**
 * What a deployment carries (#85). `lineage` is `unknown` when no artifact of the deployment contains
 * a change, and the empty lists then mean "not known", never "nothing".
 */
export interface DeploymentWorkItems {
  deployment: {
    id: string
    deployedAt?: string
    status?: string
    environment?: LineageEnvironment
  }
  lineage: 'known' | 'unknown'
  changes: (LineageChange & { artifact: string })[]
  workItems: (LineageWorkItem & { changes: string[] })[]
}

/**
 * Change lineage (#85). A work item's URI and a deployment's key hold `//`, `/` and `#`, so both
 * travel as query parameters.
 */
export const lineageApi = {
  deploymentsOfWorkItem: (uri: string): Promise<WorkItemDeployments> =>
    client.get('/work-items/deployments', { params: { uri } }).then(r => r.data),
  workItemsOfDeployment: (deploymentId: string): Promise<DeploymentWorkItems> =>
    client.get('/deployments/work-items', { params: { deploymentId } }).then(r => r.data)
}

/** Which way a neighbourhood walk follows edges from each node: along them, against them, or both. */
export type GraphDirection = 'in' | 'out' | 'both'

/** What the graph view asks for (#9, FR1). Absent filters mean every type but the meta ones. */
export interface NeighbourhoodQuery {
  nodeId: string
  depth?: number
  nodeTypes?: string[]
  edgeTypes?: string[]
  direction?: GraphDirection
}

/** A node ready to draw: `label` is the registry's displayProperty of the node, or its key. */
export interface SubgraphNode {
  id: string
  type: string
  key: string
  label: string
  distance: number
  props: Record<string, unknown>
  /**
   * Always sent by the neighbourhood. A node the graph view added from a blast radius (#21) has
   * none, because the impact answer does not carry a node's provenance.
   */
  provenance?: Provenance
}

/** An edge ready to draw. `id` is `type:from>to`, the same on every answer, so expansions merge by it. */
export interface SubgraphEdge {
  id: string
  type: string
  inverse: string
  from: string
  to: string
  confidence: number
  inferred: boolean
}

/** A bounded neighbourhood (#9): at most 500 nodes, nearest first; `truncated` says there were more. */
export interface Subgraph {
  root: string
  nodes: SubgraphNode[]
  edges: SubgraphEdge[]
  truncated: boolean
}

/**
 * The configuration item linked to a repository, in the four fields this endpoint has always sent.
 *
 * Narrower than the `ConfigurationItem` the registry declares, on purpose: this endpoint predates the
 * generic node API and callers built against it read these four. Everything a CMDB actually records -
 * criticality, support group, environment - comes back from `/nodes/ConfigurationItem/{key}` without
 * anybody widening this.
 */
export interface ServiceNowCI {
  id: string
  ciName: string
  serviceId: string
  repoId: string | null
}

/**
 * A node as the generic API renders it: the identity the server derived, the properties the
 * ontology declares, and the provenance of the statement that it exists.
 *
 * `props` is deliberately loose. The editing screens render themselves from `GET /api/v1/ontology`,
 * so tying this to a union of the generated interfaces would defeat the point: a node type added to
 * the registry has to reach the user interface without a frontend release.
 */
export interface GraphNode {
  id: string
  type: string
  key: string
  props: Record<string, unknown>
  provenance: Provenance
}

export interface NodePage {
  items: GraphNode[]
  nextCursor?: string | null
}

/** One property the server refused, with the message meant for that field's input. */
export interface PropertyError {
  field: string
  message: string
}

export interface ListOptions {
  limit?: number
  cursor?: string
}

/**
 * CRUD for any node type the registry declares.
 *
 * A node's key can contain slashes (`github.com/acme/payments`), and the server reads the segment
 * after the type as a path rather than as one encoded component, so keys are interpolated as-is.
 * That is safe here because a key only ever comes back from the server; nothing user-typed reaches
 * it without a round trip that would have failed first. A key holding `//` - an ExternalWorkItem's
 * URI (#85) - cannot travel in a path at all, so it is sent to `/by-key` as a query parameter.
 */
const nodeAddress = (
  type: NodeType | string,
  key: string
): { url: string; params?: Record<string, string> } =>
  key.includes('//')
    ? { url: `/nodes/${type}/by-key`, params: { key } }
    : { url: `/nodes/${type}/${key}` }

export const nodeApi = {
  list: (type: NodeType | string, options: ListOptions = {}): Promise<NodePage> =>
    client.get(`/nodes/${type}`, { params: options }).then(r => r.data),
  get: (type: NodeType | string, key: string): Promise<GraphNode> => {
    const { url, params } = nodeAddress(type, key)
    return client.get(url, { params }).then(r => r.data)
  },
  create: (type: NodeType | string, props: Record<string, unknown>): Promise<GraphNode> =>
    client.post(`/nodes/${type}`, { props }).then(r => r.data),
  update: (
    type: NodeType | string,
    key: string,
    props: Record<string, unknown>
  ): Promise<GraphNode> => {
    const { url, params } = nodeAddress(type, key)
    return client.put(url, { props }, { params }).then(r => r.data)
  },
  remove: (
    type: NodeType | string,
    key: string,
    options: { cascade?: boolean } = {}
  ): Promise<void> => {
    const { url, params } = nodeAddress(type, key)
    const cascade = options.cascade ? { cascade: true } : undefined
    return client
      .delete(url, { params: params || cascade ? { ...params, ...cascade } : undefined })
      .then(() => undefined)
  }
}

/** A relationship as one end of it sees it. `displayName` is what to label it with on that page. */
export interface EdgeView {
  type: string
  inverse: string
  direction: 'in' | 'out'
  displayName: string
  other: { id: string; type: string; key: string; props?: Record<string, unknown> }
  props: Record<string, unknown>
  provenance: Provenance
}

export interface EdgeWritten {
  type: string
  inverse: string
  from: { id: string; type: string; key: string }
  to: { id: string; type: string; key: string }
  props: Record<string, unknown>
  provenance: Provenance
}

export interface EdgeInput {
  type: EdgeTypeName | string
  fromId: string
  toId: string
  props?: Record<string, unknown>
}

/**
 * Relationships of any type the registry declares.
 *
 * Node ids contain slashes, so every one of these passes them in the body or as a query parameter
 * rather than as a path segment — the server cannot receive an encoded slash in a path.
 */
export const edgeApi = {
  create: (edge: EdgeInput): Promise<EdgeWritten> => client.post('/edges', edge).then(r => r.data),
  remove: (type: string, fromId: string, toId: string): Promise<void> =>
    client.delete('/edges', { params: { type, fromId, toId } }).then(() => undefined),
  forNode: (
    type: string,
    key: string,
    options: { direction?: 'in' | 'out' | 'both'; edgeType?: string } = {}
  ): Promise<EdgeView[]> =>
    client
      .get('/edges', {
        params: {
          nodeId: `${type}:${key}`,
          direction: options.direction ?? 'both',
          edgeType: options.edgeType
        }
      })
      .then(r => r.data.items)
}

/**
 * The ontology is the declared contract for what may exist in the graph. The editing screens render
 * their fields from this rather than from hand-written forms, so a node type added to the registry
 * appears in the user interface without a frontend release.
 */
export interface OntologyProperty {
  name: string
  type: 'string' | 'int' | 'float' | 'boolean' | 'instant' | 'string[]'
  required: boolean
  description: string | null
  /** Present when the registry constrains the value, so a form can offer a choice rather than a box. */
  enum?: string[]
  /** Values the property accepts (#81); the first is what a form shows as its placeholder. */
  examples?: unknown[]
  /** The shape a string value takes, such as `url` or `email`, checked by the server on write. */
  format?: string
  /** The sibling values under which the format applies, such as `{ provider: 'aws' }`. */
  formatWhen?: Record<string, string>
  /** Set when the property is kept for old writers but should no longer be relied on. */
  deprecated?: { since: string; replacedBy: string | null }
}

export interface OntologyNodeType {
  name: string
  description: string | null
  identity: string[]
  properties: OntologyProperty[]
  /** Describes the graph itself (its ontology, its sync runs) rather than the software it models. */
  meta: boolean
  /** The property a node of this type is labelled with where it is drawn (#9); null for its key. */
  displayProperty?: string | null
  /** Properties that together find a node beside its key, unique where all are present (#88). */
  alias?: string[]
  /** Questions a reader answers with this type (#81). */
  questions?: string[]
  /** Whole example nodes, each one the API accepts (#81). */
  examples?: Record<string, unknown>[]
}

export interface OntologyEdgeType {
  name: string
  description: string | null
  from: string[]
  to: string[]
  inverse: string
  properties: OntologyProperty[]
}

export interface Ontology {
  version: string
  nodeTypes: OntologyNodeType[]
  edgeTypes: OntologyEdgeType[]
  /** The provenance envelope every node and edge carries (#114). */
  provenance?: { properties: OntologyProperty[] }
}

/**
 * The actuator, for the few endpoints a deployment answers publicly (docs/DEPLOYMENT.md). Separate
 * from `apiClient` because it is not under `/api/v1`.
 */
export const actuatorClient = axios.create({ baseURL: '/actuator' })

/** What a deployment says it is running: `/actuator/info`'s `deployment` block. */
export interface DeploymentInfo {
  deployment: {
    commit: string
    version: string
    ontologyVersion: string
    profile: string
    readOnly: boolean
  }
}

export const infoApi = {
  get: (): Promise<DeploymentInfo> =>
    actuatorClient.get('/info', { headers: { Accept: 'application/json' } }).then(r => r.data)
}

export const ontologyApi = {
  get: (): Promise<Ontology> => client.get('/ontology').then(r => r.data),
  getNodeType: (type: string): Promise<OntologyNodeType> =>
    client.get(`/ontology/nodes/${type}`).then(r => r.data)
}
