import axios from 'axios'

// Node shapes come from the ontology registry, generated by ./gradlew generateOntology. Declaring
// them here as well is how the model used to drift between backend and frontend, so these are
// re-exported rather than restated. See docs/ONTOLOGY.md.
export type {
  Repository,
  Team,
  Service,
  Pipeline,
  Artifact,
  Deployment,
  Environment,
  CloudResource,
  ConfigurationItem,
  Provenance,
  NodeType,
  EdgeTypeName
} from '@/generated/ontology'
export { NODE_TYPES, EDGE_TYPES, ONTOLOGY_VERSION } from '@/generated/ontology'

import type {
  Repository,
  Team,
  Deployment,
  CloudResource,
  NodeType,
  EdgeTypeName,
  Provenance
} from '@/generated/ontology'

/**
 * The one HTTP client every call goes through. Exported so the consumer contract tests can point it
 * at a Pact mock server and exercise the real API functions rather than a copy of them.
 */
export const apiClient = axios.create({ baseURL: '/api/v1' })

const client = apiClient

export interface ImpactAnalysis {
  repoId: string
  dependents: Repository[]
  cloudResources: CloudResource[]
  deployments: Deployment[]
}

export const repositoryApi = {
  list: (): Promise<Repository[]> => client.get('/repositories').then(r => r.data),
  get: (id: string): Promise<Repository> => client.get(`/repositories/${id}`).then(r => r.data),
  create: (repo: Omit<Repository, 'id'>): Promise<Repository> =>
    client.post('/repositories', repo).then(r => r.data),
  delete: (id: string): Promise<void> => client.delete(`/repositories/${id}`).then(() => undefined),
  linkToTeam: (repoId: string, teamId: string): Promise<void> =>
    client.post(`/repositories/${repoId}/teams/${teamId}`).then(() => undefined),
  addDependency: (repoId: string, depRepoId: string): Promise<void> =>
    client.post(`/repositories/${repoId}/dependencies/${depRepoId}`).then(() => undefined)
}

export const graphApi = {
  getCloudResources: (repoId: string): Promise<CloudResource[]> =>
    client.get(`/graph/repositories/${repoId}/cloud-resources`).then(r => r.data),
  getDependencies: (repoId: string): Promise<Repository[]> =>
    client.get(`/graph/repositories/${repoId}/dependencies`).then(r => r.data),
  getDependents: (repoId: string): Promise<Repository[]> =>
    client.get(`/graph/repositories/${repoId}/dependents`).then(r => r.data),
  getDeployments: (repoId: string): Promise<Deployment[]> =>
    client.get(`/graph/repositories/${repoId}/deployments`).then(r => r.data),
  getTeam: (repoId: string): Promise<Team | null> =>
    client
      .get(`/graph/repositories/${repoId}/team`)
      .then(r => r.data)
      .catch(() => null),
  getImpact: (repoId: string): Promise<ImpactAnalysis> =>
    client.get(`/graph/repositories/${repoId}/impact`).then(r => r.data)
}

/**
 * A node as the generic API renders it: the identity the server derived, the properties the
 * ontology declares, and the provenance of the statement that it exists.
 *
 * `props` is deliberately loose. The editing screens render themselves from `GET /api/v1/ontology`,
 * so tying this to a union of the generated interfaces would defeat the point: a node type added to
 * the registry has to reach the user interface without a frontend release.
 */
export interface GraphNode {
  id: string
  type: string
  key: string
  props: Record<string, unknown>
  provenance: Provenance
}

export interface NodePage {
  items: GraphNode[]
  nextCursor?: string | null
}

/** One property the server refused, with the message meant for that field's input. */
export interface PropertyError {
  field: string
  message: string
}

export interface ListOptions {
  limit?: number
  cursor?: string
}

/**
 * CRUD for any node type the registry declares.
 *
 * A node's key can contain slashes (`github.com/acme/payments`), and the server reads the segment
 * after the type as a path rather than as one encoded component, so keys are interpolated as-is.
 * That is safe here because a key only ever comes back from the server; nothing user-typed reaches
 * it without a round trip that would have failed first.
 */
export const nodeApi = {
  list: (type: NodeType | string, options: ListOptions = {}): Promise<NodePage> =>
    client.get(`/nodes/${type}`, { params: options }).then(r => r.data),
  get: (type: NodeType | string, key: string): Promise<GraphNode> =>
    client.get(`/nodes/${type}/${key}`).then(r => r.data),
  create: (type: NodeType | string, props: Record<string, unknown>): Promise<GraphNode> =>
    client.post(`/nodes/${type}`, { props }).then(r => r.data),
  update: (
    type: NodeType | string,
    key: string,
    props: Record<string, unknown>
  ): Promise<GraphNode> => client.put(`/nodes/${type}/${key}`, { props }).then(r => r.data),
  remove: (
    type: NodeType | string,
    key: string,
    options: { cascade?: boolean } = {}
  ): Promise<void> =>
    client
      .delete(`/nodes/${type}/${key}`, { params: options.cascade ? { cascade: true } : undefined })
      .then(() => undefined)
}

/** A relationship as one end of it sees it. `displayName` is what to label it with on that page. */
export interface EdgeView {
  type: string
  inverse: string
  direction: 'in' | 'out'
  displayName: string
  other: { id: string; type: string; key: string; props?: Record<string, unknown> }
  props: Record<string, unknown>
  provenance: Provenance
}

export interface EdgeWritten {
  type: string
  inverse: string
  from: { id: string; type: string; key: string }
  to: { id: string; type: string; key: string }
  props: Record<string, unknown>
  provenance: Provenance
}

export interface EdgeInput {
  type: EdgeTypeName | string
  fromId: string
  toId: string
  props?: Record<string, unknown>
}

/**
 * Relationships of any type the registry declares.
 *
 * Node ids contain slashes, so every one of these passes them in the body or as a query parameter
 * rather than as a path segment — the server cannot receive an encoded slash in a path.
 */
export const edgeApi = {
  create: (edge: EdgeInput): Promise<EdgeWritten> => client.post('/edges', edge).then(r => r.data),
  remove: (type: string, fromId: string, toId: string): Promise<void> =>
    client.delete('/edges', { params: { type, fromId, toId } }).then(() => undefined),
  forNode: (
    type: string,
    key: string,
    options: { direction?: 'in' | 'out' | 'both'; edgeType?: string } = {}
  ): Promise<EdgeView[]> =>
    client
      .get('/edges', {
        params: {
          nodeId: `${type}:${key}`,
          direction: options.direction ?? 'both',
          edgeType: options.edgeType
        }
      })
      .then(r => r.data.items)
}

/**
 * The ontology is the declared contract for what may exist in the graph. The editing screens render
 * their fields from this rather than from hand-written forms, so a node type added to the registry
 * appears in the user interface without a frontend release.
 */
export interface OntologyProperty {
  name: string
  type: 'string' | 'int' | 'boolean' | 'instant' | 'string[]'
  required: boolean
  description: string | null
  /** Present when the registry constrains the value, so a form can offer a choice rather than a box. */
  enum?: string[]
}

export interface OntologyNodeType {
  name: string
  description: string | null
  identity: string[]
  properties: OntologyProperty[]
}

export interface OntologyEdgeType {
  name: string
  description: string | null
  from: string[]
  to: string[]
  inverse: string
  properties: OntologyProperty[]
}

export interface Ontology {
  version: string
  nodeTypes: OntologyNodeType[]
  edgeTypes: OntologyEdgeType[]
}

export const ontologyApi = {
  get: (): Promise<Ontology> => client.get('/ontology').then(r => r.data),
  getNodeType: (type: string): Promise<OntologyNodeType> =>
    client.get(`/ontology/nodes/${type}`).then(r => r.data)
}
