import { execSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { fileURLToPath, URL } from 'node:url'
import { defineConfig } from 'vitepress'

/**
 * The site's shape. Its *content* is not here: every page under `src/` is generated by
 * `scripts/generate.mjs` from a source in the repository.
 *
 * The commit and the build time are read at build time rather than baked into a generated page on
 * purpose. They change on every run, so committing them would make `npm run drift` fail forever;
 * the drift check only works because everything it compares is a pure function of the sources.
 */
const repoFile = (path: string) => fileURLToPath(new URL(`../../${path}`, import.meta.url))

const ontology = JSON.parse(readFileSync(repoFile('backend/src/main/resources/ontology/v1/ontology.json'), 'utf8'))

const commit =
  process.env.GITHUB_SHA ??
  (() => {
    try {
      return execSync('git rev-parse HEAD', { encoding: 'utf8' }).trim()
    } catch {
      return 'unknown'
    }
  })()

const builtAt = new Date().toISOString().replace(/\.\d+Z$/, 'Z')

export default defineConfig({
  title: 'SDLC Knowledge Graph',
  description:
    'A knowledge graph over code repositories: how a commit becomes a running service, and what that service depends on.',
  srcDir: 'src',
  cleanUrls: true,
  // A link to a page that does not exist is a broken promise to a reader, so it fails the build
  // rather than shipping.
  ignoreDeadLinks: false,
  head: [['meta', { name: 'theme-color', content: '#2b6cb0' }]],
  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/ontology' },
      { text: 'Reference', link: '/reference/ontology' },
      { text: 'Decisions', link: '/adr/' },
      { text: 'Roadmap', link: '/reference/roadmap' },
      { text: 'GitHub', link: 'https://github.com/MaximumTrainer/SdlcKnowledgeGraph' }
    ],
    sidebar: [
      {
        text: 'Guide',
        items: [
          { text: 'Ontology', link: '/guide/ontology' },
          { text: 'Adapters', link: '/guide/adapters' },
          { text: 'Testing', link: '/guide/testing' }
        ]
      },
      {
        text: 'Reference',
        items: [
          { text: 'Ontology reference', link: '/reference/ontology' },
          { text: 'REST API', link: '/reference/api' },
          { text: 'Roadmap', link: '/reference/roadmap' }
        ]
      },
      { text: 'Decisions', items: [{ text: 'All records', link: '/adr/' }] }
    ],
    socialLinks: [{ icon: 'github', link: 'https://github.com/MaximumTrainer/SdlcKnowledgeGraph' }],
    search: { provider: 'local' },
    editLink: {
      pattern:
        'https://github.com/MaximumTrainer/SdlcKnowledgeGraph/edit/main/:path?message=note%3A%20pages%20are%20generated%20from%20repository%20sources',
      text: 'This page is generated — edit its source'
    },
    footer: {
      message: `ontology v${ontology.version} · build ${commit.slice(0, 7)} · generated ${builtAt}`,
      copyright: 'Generated from the repository. Nothing on this site is written by hand.'
    }
  }
})
